### ISSUE TITLE
Convert variant forms

### ISSUE THREAD

**Issue by jmccrae** [elexis-eu/tei2ontolex#3]
Convert a form as shown in the [variant section of the TEI Lex-0 spec](https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#index.xml-body.1_div.4_div.6)

TEI Lex-0
```xml   
   <entry xml:id="Flussschifffahrt" xml:lang="de" type="compound">
        <form type="lemma">
            <orth type="segmeted">
                <seg>Fluss</seg>
                <seg>schifffahrt</seg>
            </orth>
            <form type="variant">
                <orth>
                    <seg>Fluss</seg>
                    <pc>-</pc>
                    <seg>Schifffahrt</seg>
                </orth>
            </form>
            <form type="variant">
                <orth notAfter="1996">
                    <seg>Fluß</seg>
                    <seg>schifffahrt</seg>
                </orth>
                <usg type="time">Vor 1996 Rechtschreibung Reform</usg>
            </form>
        </form>
    </entry>
```

Expected OntoLex

```turtle
<#Flussschifffahrt> a ontolex:LexicalEntry ;
  ontolex:canonicalForm [ 
    ontolex:writtenRep "Flussschifffahrt"@de , 
    "Fluss-Schifffahrt"@de, "Flußschifffahrt"@de 
  ] .
```

**Comment by laurentromary** [comment]
I have adapted the stylesheet so that it generates the following for variants in the Petit Larousse Illustré. Can you confirm it is correct (XML serialization so far - we'll adapt to the other one when all features are set).
```XML
 <ontolex:canonicalForm>
      <rdf:Description>
        <ontolex:writtenRep xml:lang="fr">ABOIEMENT</ontolex:writtenRep>
        <ontolex:writtenRep xml:lang="fr">ABOÎMENT</ontolex:writtenRep>
        <ontolex:phoneticRep xml:lang="fr">boi-man</ontolex:phoneticRep>
        <ontolex:writtenRep xml:lang="fr">ABOÎMENT</ontolex:writtenRep>
      </rdf:Description>
</ontolex:canonicalForm>
```

**Comment by jmccrae** [comment]
Yes, that looks good to me.

**Comment by laurentromary** [comment]
OK. Closing the issue !

**Comment by jmccrae** [comment]
The test still does not work though

```
======================================================================
FAIL: test3 (__main__.TestTEI2OntoLex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 66, in test3
    compare_rdf_graphs(expected, actual, self)
  File "test.py", line 31, in compare_rdf_graphs
    "A triple was missing: %s %s %s" % (s.n3(), p.n3(), o.n3()))
AssertionError: False is not true : A triple was missing: <file:///home/jmccrae/projects/elexis/tei2ontolex/tests/test3.ttl#Flussschifffahrt> <http://www.w3.org/ns/lemon/ontolex#canonicalForm> _:ub3bL4C25

----------------------------------------------------------------------
```

**Comment by laurentromary** [comment]
Can you identify where the problem is?

**Comment by jmccrae** [comment]
Recent error is
```
Missing:
('[]', '<http://www.w3.org/ns/lemon/ontolex#writtenRep>', '"Flußschifffahrt"@de')
('[]', '<http://www.w3.org/ns/lemon/ontolex#phoneticRep>', '"ow.\\"sa.mabɪnˈlaːdn̹"@en-fonipa')
('[]', '<http://www.w3.org/ns/lemon/ontolex#writtenRep>', '"Fluss-Schifffahrt"@de')
('[]', '<http://www.w3.org/ns/lemon/ontolex#writtenRep>', '"Flussschifffahrt"@de')
Incorrect:
('[]', '<http://www.w3.org/ns/lemon/ontolex#phoneticRep>', '"""\n                ow."sa.ma\n                bɪn\n                ˈlaːdn̹\n            """@fr')
('[]', '<http://www.w3.org/ns/lemon/ontolex#writtenRep>', '"""\n                Fluss\n                schifffahrt\n            """@fr')
('[]', '<http://www.w3.org/ns/lemon/ontolex#writtenRep>', '"""\n                    Fluss\n                    \n                    Schifffahrt\n                """@fr')
('[]', '<http://www.w3.org/ns/lemon/ontolex#writtenRep>', '"""\n                    Fluß\n                    schifffahrt\n                """@fr')
```

Seems we need to squash extra whitespace. Languages is also not correct as in #1

**Comment by laurentromary** [comment]
This one should also been set. @jmccrae can you check for test3 and telle whether you would possibly keep the information about dating and usage (and how)?

**Comment by jmccrae** [comment]
It seems the `<pc>` tag is being dropped and an extra `<lexinfo:register>` is generated

```
Missing:
('[]', '<http://www.w3.org/ns/lemon/ontolex#writtenRep>', '"Fluss-Schifffahrt"@de')
Incorrect:
('[]', '<http://www.lexinfo.net/ontology/2.0/lexinfo#register>', '[]')
('[]', '<http://www.w3.org/ns/lemon/ontolex#writtenRep>', '"FlussSchifffahrt"@de')
```

**Comment by laurentromary** [comment]
OK. I have corrected the `<pc>` (which I normally  drop elsewhere (intermediate things like ,;. etc.). But  the `<usg>` is the source of `<lexinfo:register>`: do you want me to drop this altogether?

**Comment by jmccrae** [comment]
Test passes now
